services:
  daily-fret:
    image: ghcr.io/punishergui/faithfulfret:rewrite-app
    container_name: daily-fret
    restart: unless-stopped
    pull_policy: always
    ports:
      - "3000:9999"
    environment:
      - PORT=9999
      - NODE_ENV=production
    volumes:
      - /data:/data
